apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: rayane001/hello-app
  newTag: 0e00d0dc80395accc5a0a6e510ad67c62b95079d