apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-app
  image: rayane001/main-python:latest
  newTag: 203efc1d2a0273bff0c9324234d23967e8df8b0f

