apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: rayane001/hello-app
  newTag: b09ca343f184ab159cd947de94fa388dc06eb1d3